name: Update Dependencies
on:
  schedule:
    - cron: '0 5 * * 3,6'
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v4

      - name: Update dependencies
        run: |
          npx taze -w
          npm install

      - name: Commit updates
        run: |
         git config user.name "github-actions[bot]"
         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add .
         git commit -m "chore: bump dependencies"
         git push
